const fs = require("fs");
const path = require("path");

const dirPath = path.join(__dirname, "files");
console.log(dirPath);

// for (let i = 1; i <= 5; i++) {
//   fs.writeFileSync(
//     `${dirPath}/hello${i}.txt`,
//     "this is text file generated by the loop"
//   );
// }

fs.readdir(dirPath, (err, file) => {
  console.log(file);
});
